// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
	"requestEth/internal/conf"
	"requestEth/internal/server"
	"requestEth/internal/service"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(confServer *conf.Server, data *conf.Data, logger log.Logger) (*kratos.App, func(), error) {
	transactionService := service.NewTransactionService()
	grpcServer := server.NewGRPCServer(confServer, transactionService, logger)
	httpServer := server.NewHTTPServer(confServer, transactionService, logger)
	app := newApp(logger, grpcServer, httpServer)
	return app, func() {
	}, nil
}
