server:
  http:
    addr: 0.0.0.0:8001
    timeout: 30s
  grpc:
    addr: 0.0.0.0:9001
    timeout: 30s
data:
  database:
    driver: mysql
    source: root:root@tcp(127.0.0.1:3306)/test
  redis:
    addr: 127.0.0.1:6379
    read_timeout: 0.2s
    write_timeout: 0.2s
eth:
  bsc:
    addr: https://data-seed-prebsc-1-s3.binance.org:8545
